Repository 134talk/frontend, pull requests merged in 2023-05, with the labels that each got.

#69 Feat/login
  .gitignore
  src/pages/LogInPage.tsx
  src/shared/constants/Test.tsx
  src/shared/constants/constants.ts
Labels: feature

#70 Develop
  .gitignore
  src/pages/LogInPage.tsx
  src/shared/constants/Test.tsx
  src/shared/constants/constants.ts
  src/shared/utils/Device.tsx
Labels: feature

#80 Feat/members
  src/components/common/BottomTab.tsx
  src/components/common/Test.tsx
  src/pages/ChatListPage.tsx
  src/pages/MembersPage.tsx
  src/pages/RoomsPage.tsx
  src/shared/utils/RouterList.tsx
Labels: feature

#79 Feat/nickname
  src/pages/NicknameGuidePage.tsx
  src/pages/NicknamePage.tsx
  src/pages/NicknameResultPage.tsx
  src/shared/utils/RouterList.tsx
Labels: feature

#84 feat. ui 공통 Button 개발
  src/ui/Button.tsx
  src/ui/Test.tsx
  src/ui/index.ts
Labels: feature

#86 Feat/UI
  src/ui/ProfileImg.tsx
  src/ui/index.ts
Labels: feature

#87 feat. 공통 버튼 px -> rem 변경 (#83)
  src/ui/Button.tsx
Labels: feature

#98 Feat/chat
  public/assets/icons/check.svg
  public/assets/icons/leftArrow.svg
  src/components/common/Profile.tsx
  src/ui/ProfileImg.tsx
Labels: feature

#100 Feat/sign
  public/assets/icons/admin-active.svg
  public/assets/icons/admin.svg
  public/assets/icons/member-active.svg
  public/assets/icons/member.svg
  public/assets/icons/triangle-exclamation.svg
  public/assets/logos/logo-color.svg
  src/components/index.ts
  src/components/sign/ButtonColumn.tsx
  src/components/sign/Message.tsx
  src/components/sign/SignButtonColumn.tsx
  src/components/sign/SignInputColumn.tsx
  src/components/sign/Test.tsx
  src/components/sign/Title.tsx
  src/components/sign/buttonColumn.style.ts
  src/components/sign/message.style.ts
  src/components/sign/signButtonColumn.style.ts
  src/components/sign/signInputColumn.style.ts
  src/components/sign/title.style.ts
  src/pages/SignPage.tsx
  src/pages/SignSelectPage.tsx
  src/pages/signSelectPage.style.ts
  src/shared/constants/icons.ts
  src/shared/styles/globalStyle.ts
  src/shared/utils/Device.tsx
  src/ui/Button.tsx
  src/ui/Input.tsx
  src/ui/SignButton.tsx
  src/ui/index.ts
  src/ui/input.style.ts
  src/ui/signButton.style.ts
Labels: feature

#101 Feat/login
  public/assets/icons/kakao.svg
  public/assets/logos/logo.svg
  src/components/logIn/Test.tsx
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
  src/shared/constants/icons.ts
  src/ui/KakaoButton.tsx
  src/ui/index.ts
  src/ui/kakaoButton.style.ts
Labels: feature

#103 Feat/nickname
  src/components/index.ts
  src/components/nickname/ButtonWrap.tsx
  src/components/nickname/RadioSelection.tsx
  src/components/nickname/SurveyLegend.tsx
  src/components/nickname/SurveySheet.tsx
  src/components/nickname/Test.tsx
  src/components/nickname/buttonWrap.style.ts
  src/components/nickname/radioSelection.style.ts
  src/components/nickname/surveyLegend.style.ts
  src/components/nickname/surveySheet.style.ts
  src/pages/NicknameGuidePage.tsx
  src/pages/NicknamePage.tsx
  src/pages/NicknameResultPage.tsx
  src/pages/nicknameGuidePage.style.ts
  src/pages/nicknameResultPage.style.ts
  src/shared/constants/constants.ts
  src/shared/styles/globalStyle.ts
  src/ui/Button.tsx
Labels: feature

#106 Feat/bottom tab
  public/assets/icons/chat-active.svg
  public/assets/icons/chat.svg
  public/assets/icons/report-active.svg
  public/assets/icons/report.svg
  public/assets/icons/user-active.svg
  public/assets/icons/user.svg
  public/assets/icons/users-active.svg
  public/assets/icons/users.svg
  public/manifest.json
  src/components/common/BottomTab.tsx
  src/components/index.ts
  src/pages/NicknameResultPage.tsx
  src/shared/constants/icons.ts
  src/shared/utils/Device.tsx
  src/shared/utils/Router.tsx
  src/shared/utils/RouterList.tsx
Labels: feature

#107 Feat/login 배경색 변경 #3
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
Labels: feature

#110 Feat/chat
  package.json
  public/index.html
  src/components/chat/Test.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/common/Profile.tsx
  src/pages/ChatPage.tsx
  src/shared/constants/icons.ts
  src/ui/Spinner.tsx
  yarn.lock
Labels: feature

#112 Feat/members
  public/assets/icons/search.svg
  public/assets/icons/share.svg
  public/assets/icons/user-active.svg
  src/components/common/BottomTab.tsx
  src/components/common/SearchBar.tsx
  src/components/index.ts
  src/components/members/Test.tsx
  src/components/members/TopBar.tsx
  src/pages/MembersPage.tsx
  src/shared/constants/icons.ts
  src/shared/utils/Device.tsx
  src/ui/Button.tsx
Labels: feature

#113 Feat/login
  public/assets/icons/share.svg
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
  src/shared/utils/Device.tsx
  src/ui/Button.tsx
Labels: feature

#115 Feat/members 참가자 목록 스타일 수정 #20
  src/pages/MembersPage.tsx
Labels: feature

#120 Feat/chat list
  public/assets/icons/add.svg
  public/assets/icons/cancel.svg
  public/assets/icons/close.svg
  public/assets/icons/left-arrow.svg
  public/assets/icons/reload.svg
  public/assets/icons/setting.svg
  src/components/chatList/ChatBox.tsx
  src/components/chatList/chatBox.style.ts
  src/components/common/NavBar.tsx
  src/components/common/SearchBar.tsx
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/index.ts
  src/components/members/TopBar.tsx
  src/components/rooms/Test.tsx
  src/pages/ChatListPage.tsx
  src/pages/MembersPage.tsx
  src/pages/chatListPage.style.ts
  src/shared/constants/icons.ts
  src/ui/Chip.tsx
  src/ui/chip.style.ts
  src/ui/index.ts
Labels: feature

#117 feat. 공통 Profile 컴포넌트 프롭스 수정 #97
  src/components/common/Profile.tsx
Labels: feature

#122 Feat/members
  src/components/common/NavBar.tsx
  src/components/common/searchBar.style.ts
  src/pages/MembersPage.tsx
Labels: feature

#123 feat. 대화 대기중 화면 개발 #35 & 자기소개 화면 개발 #37
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/pages/ChatPage.tsx
  src/ui/Spinner.tsx
Labels: feature

#127 Feat/chat
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/ui/index.ts
Labels: feature

#128 Feat/chat
  public/assets/cards/card-selected.svg
  public/assets/cards/card.svg
  src/components/chat/KeywordScreen.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/constants/constants.ts
  src/shared/constants/icons.ts
Labels: feature

#136 Feat/chat
  public/assets/icons/chat-left-arrow.svg
  public/assets/icons/chat-right-arrow.svg
  public/assets/icons/close-black.svg
  public/assets/icons/leftArrow.svg
  src/components/chat/EmotionModal.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/common/BottomModal.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/constants/icons.ts
  src/ui/ProfileImg.tsx
Labels: feature

#139 Feat/chat list
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/BottomButtonTab.tsx
  src/components/common/BottomTab.tsx
  src/components/common/NavBar.tsx
  src/components/common/bottomButtonTab.style.ts
  src/components/common/bottomTab.style.ts
  src/components/common/navBar.style.ts
  src/components/index.ts
  src/pages/ChatListPage.tsx
  src/pages/chatListPage.style.ts
  src/shared/constants/icons.ts
  src/ui/Chip.tsx
  src/ui/chip.style.ts
Labels: feature

#140 Feat/chat
  package.json
  public/assets/cards/violet-card.svg
  src/App.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/common/BottomModal.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/constants/cards.ts
  src/shared/constants/icons.ts
  yarn.lock
Labels: feature

#143 feat. mockup 작업 & status-bar/indicator 작업 완료
  public/assets/icons/indicator.svg
  public/assets/icons/phone-mockup.svg
  public/assets/icons/status-bar.svg
  src/App.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/EmotionModal.tsx
  src/components/common/BottomModal.tsx
  src/shared/constants/icons.ts
  src/shared/utils/Device.tsx
Labels: feature

#144 Feat/members
  src/pages/MembersPage.tsx
  src/shared/hooks/useSearchKeyword.ts
Labels: feature

#146 Feat/chat list
  src/App.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/pages/chatListPage.style.ts
  src/shared/styles/globalStyle.ts
Labels: feature

#147 Deploy
  src/App.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/pages/chatListPage.style.ts
  src/shared/styles/globalStyle.ts
Labels: feature

#149 Feat/members
  public/assets/icons/link.svg
  src/App.tsx
  src/components/common/BaseModal.tsx
  src/components/common/NavBar.tsx
  src/components/index.ts
  src/components/members/InviteModal.tsx
  src/pages/MembersPage.tsx
  src/pages/membersPage.style.ts
  src/shared/constants/icons.ts
  src/ui/Button.tsx
Labels: feature

#151 Feat/chat
  public/assets/icons/chat-notify.svg
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ExitConfirmModal.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/constants/icons.ts
Labels: feature

#153 feat. InviteModal 임포트 수정
  src/components/index.ts
Labels: feature

#155 Feat/chat list 대화 설정 모달 개발 #81
  src/components/chatList/CheckModal.tsx
  src/components/chatList/SettingModal.tsx
  src/components/chatList/checkModal.style.ts
  src/components/chatList/settingModal.style.ts
  src/components/common/BottomModal.tsx
  src/components/common/NavBar.tsx
  src/components/index.ts
  src/pages/ChatListPage.tsx
  src/pages/chatListPage.style.ts
Labels: feature

#157 Feat/members 카카오톡 공유 모달 개발 #22 & #23
  src/App.tsx
  src/components/members/InviteModal.tsx
  src/components/members/inviteModal.style.ts
  src/pages/MembersPage.tsx
Labels: feature

#158 Feat/chat guide
  package.json
  public/assets/guide/guide01.svg
  public/assets/guide/guide02.svg
  public/assets/guide/guide03.svg
  public/assets/guide/guide04.svg
  public/assets/guide/guide05.svg
  public/assets/guide/guide06.svg
  public/assets/guide/guide07.svg
  public/assets/icons/skip.svg
  src/components/chatList/ChatBox.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/GuideModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/chatList/guideModal.style.ts
  src/components/common/FullModal.tsx
  src/components/index.ts
  src/pages/ChatListPage.tsx
  src/shared/constants/guideImgs.ts
  src/shared/constants/icons.ts
  yarn.lock
Labels: feature

#159 Develop
  package.json
  public/assets/guide/guide01.svg
  public/assets/guide/guide02.svg
  public/assets/guide/guide03.svg
  public/assets/guide/guide04.svg
  public/assets/guide/guide05.svg
  public/assets/guide/guide06.svg
  public/assets/guide/guide07.svg
  public/assets/icons/skip.svg
  src/App.tsx
  src/components/chatList/ChatBox.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/GuideModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/chatList/guideModal.style.ts
  src/components/common/FullModal.tsx
  src/components/index.ts
  src/components/members/InviteModal.tsx
  src/components/members/inviteModal.style.ts
  src/pages/ChatListPage.tsx
  src/pages/MembersPage.tsx
  src/shared/constants/guideImgs.ts
  src/shared/constants/icons.ts
  yarn.lock
Labels: feature

#160 Feat/chat guide
  src/components/chatList/guideModal.style.ts
  src/components/common/FullModal.tsx
Labels: feature

#163 Deploy
  .github/workflows/deploy.yml
Labels: deploy

#164 cicd 환경변수 git secrets 추가
  .github/workflows/deploy.yml
Labels: deploy

#165 Deploy
  .github/workflows/deploy.yml
Labels: deploy

#166 Feat/cicd
  .github/workflows/deploy.yml
  src/shared/api/Test.tsx
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/reportApi.ts
  src/shared/api/userApi.ts
Labels: feature, deploy

#167 Feat/chat
  public/assets/cards/card-selected.svg
  public/assets/emotions/angry.svg
  public/assets/emotions/hug.svg
  public/assets/emotions/like.svg
  public/assets/emotions/love.svg
  public/assets/emotions/right.svg
  public/assets/emotions/sad.svg
  public/assets/icons/rotate.svg
  public/assets/icons/shadow.svg
  src/components/chat/Card.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/common/BottomModal.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/constants/constants.ts
  src/shared/constants/icons.ts
  src/shared/utils/Device.tsx
  src/ui/Emotion.tsx
  src/ui/Spinner.tsx
  src/ui/index.ts
Labels: feature
