Repository 134talk/frontend, pull requests merged in 2023-07, with the labels that each got.

#270 전역 padding 수정, scroll, nav 스타일 코드 수정
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/Bubble.tsx
  src/components/common/NavBar.tsx
  src/components/common/bubble.style.ts
  src/components/common/fullModal.style.ts
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/nickname/surveyLegend.style.ts
  src/components/nickname/surveySheet.style.ts
  src/components/report/ChatDetail.tsx
  src/components/report/FeedbackDetail.tsx
  src/components/report/MemberDetail.tsx
  src/components/report/StatusDetail.tsx
  src/components/report/chatDetail.style.ts
  src/components/report/feedbackDetail.style.ts
  src/components/report/memberDetail.style.ts
  src/components/report/statusDetail.style.ts
  src/components/user/reportMenu.style.ts
  src/pages/ChatListPage.tsx
  src/pages/LogInPage.tsx
  src/pages/MemberReportPage.tsx
  src/pages/MembersPage.tsx
  src/pages/ReportDetailPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/UserReportPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/loginPage.style.ts
  src/pages/memberReportPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/nicknameGuidePage.style.ts
  src/pages/nicknameResultPage.style.ts
  src/pages/reportDetailPage.style.ts
  src/pages/reportPage.style.ts
  src/pages/signPage.style.ts
  src/pages/signSelectPage.style.ts
  src/pages/userPage.style.ts
  src/pages/userReportPage.style.ts
  src/shared/styles/globalStyle.ts
  src/shared/utils/Device.tsx
  src/ui/Loader.tsx
  src/ui/background.style.ts
  src/ui/loader.style.ts
Labels: feature, refactoring

#271 Feat/sol
  src/components/chatList/ChatBox.tsx
  src/components/chatList/SettingModal.tsx
  src/components/chatList/chatBox.style.ts
  src/components/chatList/createModal.style.ts
  src/components/chatList/guideModal.style.ts
  src/components/chatList/settingModal.style.ts
  src/components/common/BottomTab.tsx
  src/components/common/navBar.style.ts
  src/pages/ChatListPage.tsx
  src/shared/query/useChatList.ts
  src/ui/chip.style.ts
Labels: bug, feature

#272 Feat/chat
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/feedback/FeedOptionReminder.tsx
  src/components/feedback/FeedReminderModal.tsx
  src/components/feedback/FeedRequirement.tsx
  src/components/feedback/StatusReminder.tsx
  src/components/feedback/statusReminder.style.ts
  src/pages/ChatPage.tsx
  src/shared/api/reportApi.ts
  src/shared/constants/constants.ts
  src/shared/query/useFeedRequirement.ts
Labels: feature

#274 Feat/chat
  src/components/chat/ChatTutorial.tsx
  src/components/chat/tutorial.style.ts
Labels: feature

#275 feat. chatTutorial 스타일 파일명 수정
  src/components/chat/ChatTutorial.tsx
  src/components/chat/chatTutorial.style.ts
Labels: feature

#277 Feat/chat
  src/components/chat/ChatTutorial.tsx
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
  src/shared/hooks/useA2hs.ts
  src/ui/Button.tsx
  src/ui/button.style.ts
Labels: feature

#278 스타일 수정
  src/components/chatList/chatBox.style.ts
  src/components/report/ChatDetail.tsx
  src/pages/MemberReportPage.tsx
Labels: feature

#279 Feat/chat
  public/assets/icons/ios-share.svg
  src/components/common/InstallModal.tsx
  src/components/common/installModal.style.ts
  src/components/index.ts
  src/pages/LogInPage.tsx
  src/shared/constants/icons.ts
  src/shared/utils/deviceDetector.ts
Labels: feature

#280 Deploy
  public/assets/icons/ios-share.svg
  src/components/chatList/chatBox.style.ts
  src/components/common/InstallModal.tsx
  src/components/common/installModal.style.ts
  src/components/index.ts
  src/components/report/ChatDetail.tsx
  src/pages/LogInPage.tsx
  src/pages/MemberReportPage.tsx
  src/shared/constants/icons.ts
  src/shared/utils/deviceDetector.ts
Labels: deploy

#281 Feat/chat
  src/components/feedback/feedOptionCheck.style.ts
  src/components/feedback/feedRequirement.style.ts
  src/components/feedback/progressBar.style.ts
  src/components/feedback/statusReminder.style.ts
  src/pages/LogInPage.tsx
  src/shared/utils/deviceDetector.ts
Labels: feature

#282 Deploy
  src/components/feedback/feedOptionCheck.style.ts
  src/components/feedback/feedRequirement.style.ts
  src/components/feedback/progressBar.style.ts
  src/components/feedback/statusReminder.style.ts
  src/pages/LogInPage.tsx
  src/shared/utils/deviceDetector.ts
Labels: deploy

#283 feat. 스타일 수정
  src/components/common/navBar.style.ts
Labels: feature

#284 Feat/chat
  src/pages/LogInPage.tsx
Labels: feature

#285 Deploy
  src/components/common/navBar.style.ts
  src/pages/LogInPage.tsx
Labels: deploy

#286 feat. padding 추가
  src/components/chatList/guideModal.style.ts
Labels: feature

#287 Feat/chat
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/introductionScreen.style.ts
  src/components/chat/keywordScreen.style.ts
  src/components/chat/selectionScreen.style.ts
  src/components/chat/waitingScreen.style.ts
  src/components/common/navBar.style.ts
  src/components/feedback/feedOptionReminder.style.ts
  src/pages/ChatPage.tsx
  src/shared/query/useFeedRequirement.ts
  src/shared/query/useFeedUser.ts
  src/shared/store/chatSlice.ts
  src/shared/store/socketMiddleware.ts
  src/ui/Emotion.tsx
  src/ui/emotion.style.ts
Labels: feature

#290 feat. scroll padding bottom 수정
  src/pages/chatListPage.style.ts
  src/pages/membersPage.style.ts
Labels: feature

#292 Feat/chat
  src/components/chat/Card.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/chat/card.style.ts
  src/components/chat/chatNotifyScreen.style.ts
  src/components/chat/chatScreen.style.ts
  src/components/chat/chatSideNav.style.ts
  src/components/chat/chatTutorial.style.ts
  src/components/chat/emotionModal.style.ts
  src/components/chat/exitConfirmModal.style.ts
  src/components/chat/introductionScreen.style.ts
  src/components/chat/keywordList.style.ts
  src/components/chat/keywordScreen.style.ts
  src/components/chat/selectionScreen.style.ts
  src/components/chat/userList.style.ts
  src/components/chat/waitingScreen.style.ts
  src/components/common/profile.style.ts
  src/components/feedback/StatusReminder.tsx
  src/components/feedback/feedOptionCheck.style.ts
  src/components/feedback/feedOptionReminder.style.ts
  src/components/feedback/feedReminderModal.style.ts
  src/components/feedback/feedRequirement.style.ts
  src/components/feedback/progressBar.style.ts
  src/components/feedback/statusReminder.style.ts
  src/components/feedback/statusSlider.style.ts
  src/pages/ChatPage.tsx
  src/shared/styles/theme.ts
Labels: feature

#293 Deploy
  src/components/chat/Card.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/chat/card.style.ts
  src/components/chat/chatNotifyScreen.style.ts
  src/components/chat/chatScreen.style.ts
  src/components/chat/chatSideNav.style.ts
  src/components/chat/chatTutorial.style.ts
  src/components/chat/emotionModal.style.ts
  src/components/chat/exitConfirmModal.style.ts
  src/components/chat/introductionScreen.style.ts
  src/components/chat/keywordList.style.ts
  src/components/chat/keywordScreen.style.ts
  src/components/chat/selectionScreen.style.ts
  src/components/chat/userList.style.ts
  src/components/chat/waitingScreen.style.ts
  src/components/common/profile.style.ts
  src/components/feedback/StatusReminder.tsx
  src/components/feedback/feedOptionCheck.style.ts
  src/components/feedback/feedOptionReminder.style.ts
  src/components/feedback/feedReminderModal.style.ts
  src/components/feedback/feedRequirement.style.ts
  src/components/feedback/progressBar.style.ts
  src/components/feedback/statusReminder.style.ts
  src/components/feedback/statusSlider.style.ts
  src/pages/ChatPage.tsx
  src/shared/styles/theme.ts
Labels: deploy

#294 feat. emoticon mapping constant key 수정, padding 수정
  src/components/common/bubble.style.ts
  src/components/user/reportMenu.style.ts
  src/pages/MemberReportPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/userPage.style.ts
  src/shared/hooks/useChartIcons.ts
Labels: feature

#295 Deploy
  src/components/common/bubble.style.ts
  src/components/user/reportMenu.style.ts
  src/pages/MemberReportPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/userPage.style.ts
  src/shared/hooks/useChartIcons.ts
Labels: deploy

#296 feat. 대화 목록 검색 에러 처리 추가
  src/pages/ChatListPage.tsx
  src/shared/query/useChatList.ts
Labels: feature

#297 Develop
  src/pages/ChatListPage.tsx
  src/shared/query/useChatList.ts
Labels: feature

#298 fix. 새 대화 뱃지 위치 수정
  src/components/common/BottomTab.tsx
  src/components/common/bottomTab.style.ts
Labels: bug

#299 Deploy
  src/components/common/BottomTab.tsx
  src/components/common/bottomTab.style.ts
Labels: deploy

#303 feat. 스타일 수정, 데이터 없을 시 예외 처리 문구 추가
  src/components/common/bubble.style.ts
  src/components/common/emotionData.style.ts
  src/components/user/Emotion.tsx
  src/components/user/Sentence.tsx
  src/components/user/sentence.style.ts
  src/pages/MemberReportPage.tsx
  src/pages/UserReportPage.tsx
Labels: bug, feature

#304 Deploy
  src/components/common/bubble.style.ts
  src/components/common/emotionData.style.ts
  src/components/user/Emotion.tsx
  src/components/user/Sentence.tsx
  src/components/user/sentence.style.ts
  src/pages/MemberReportPage.tsx
  src/pages/UserReportPage.tsx
Labels: deploy

#305 feat. 대화 목록 검색 api url 변경
  src/shared/api/chatApi.ts
Labels: feature

#306 Release
  src/shared/api/chatApi.ts
Labels: deploy

#307 feat. 임시 테스트 로그인 폼 적용
  src/components/TestLogin.tsx
  src/pages/LogInPage.tsx
Labels: feature

#308 Release
  src/components/TestLogin.tsx
  src/pages/LogInPage.tsx
Labels: deploy

#314 fix. #313
  src/pages/SignPage.tsx
Labels: bug

#315 Release
  src/pages/SignPage.tsx
Labels: deploy

#316 Fix/dam
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/selectionScreen.style.ts
  src/components/common/EmotionData.tsx
  src/components/common/navBar.style.ts
  src/components/feedback/FeedOptionReminder.tsx
  src/components/index.ts
  src/components/login/AddToHomeScreen.tsx
  src/components/login/InstallModal.tsx
  src/components/login/addToHomeScreen.style.ts
  src/components/login/installModal.style.ts
  src/pages/LogInPage.tsx
  src/shared/constants/constants.ts
  src/shared/query/useFeedOption.ts
Labels: bug

#317 Deploy
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/selectionScreen.style.ts
  src/components/common/EmotionData.tsx
  src/components/common/navBar.style.ts
  src/components/feedback/FeedOptionReminder.tsx
  src/components/index.ts
  src/components/login/AddToHomeScreen.tsx
  src/components/login/InstallModal.tsx
  src/components/login/addToHomeScreen.style.ts
  src/components/login/installModal.style.ts
  src/pages/LogInPage.tsx
  src/shared/constants/constants.ts
  src/shared/query/useFeedOption.ts
Labels: deploy

#319 Deploy
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/ChatTutorial.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/feedback/FeedOptionCheck.tsx
  src/components/feedback/FeedOptionReminder.tsx
  src/components/feedback/feedOptionReminder.style.ts
  src/shared/hooks/useEmotionChange.ts
  src/shared/hooks/useUserData.ts
  src/shared/hooks/useUserFeedbacks.ts
  src/shared/query/useFeedRequirement.ts
  src/shared/store/chatSlice.ts
  src/shared/store/socketMiddleware.ts
Labels: deploy

#325 Fix/dam
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/SelectionScreen.tsx
  src/pages/ChatPage.tsx
  src/shared/hooks/useEmotionChange.ts
  src/shared/store/socketMiddleware.ts
Labels: bug

#326 Deploy
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/SelectionScreen.tsx
  src/pages/ChatPage.tsx
  src/shared/hooks/useEmotionChange.ts
  src/shared/store/socketMiddleware.ts
Labels: deploy

#323 fix. #320
  src/pages/ReportPage.tsx
Labels: bug

#327 Fix/sol
  src/pages/ReportPage.tsx
Labels: bug

#328 Deploy
  src/pages/ReportPage.tsx
Labels: deploy

#329 fix. test
  src/components/chat/SelectionScreen.tsx
Labels: bug

#330 deploy
  src/components/chat/SelectionScreen.tsx
Labels: deploy

#331 fix. 질문 중복 선택 버그 수정
  src/components/chat/SelectionScreen.tsx
Labels: bug

#332 Deploy
  src/components/chat/SelectionScreen.tsx
Labels: deploy

#333 Feat/sol
  src/components/TestLogin.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/BottomTab.tsx
  src/components/common/Nav.tsx
  src/components/common/bottomTab.style.ts
  src/components/common/nav.style.ts
  src/components/index.ts
  src/components/report/chatDetail.style.ts
  src/components/report/feedbackDetail.style.ts
  src/components/report/memberDetail.style.ts
  src/components/report/statusDetail.style.ts
  src/components/user/UserProfile.tsx
  src/components/user/userProfile.style.ts
  src/pages/LogInPage.tsx
  src/pages/MembersPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/memberReportPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/userPage.style.ts
  src/shared/utils/Device.tsx
  src/shared/utils/Router.tsx
Labels: feature

#334 Release
  src/components/TestLogin.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/BottomTab.tsx
  src/components/common/Nav.tsx
  src/components/common/bottomTab.style.ts
  src/components/common/nav.style.ts
  src/components/index.ts
  src/components/report/chatDetail.style.ts
  src/components/report/feedbackDetail.style.ts
  src/components/report/memberDetail.style.ts
  src/components/report/statusDetail.style.ts
  src/components/user/UserProfile.tsx
  src/components/user/userProfile.style.ts
  src/pages/LogInPage.tsx
  src/pages/MembersPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/memberReportPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/userPage.style.ts
  src/shared/utils/Device.tsx
  src/shared/utils/Router.tsx
Labels: deploy

#337 Feat/dam
  src/components/chat/Card.tsx
  src/components/chat/card.style.ts
  src/components/common/BottomButtonTab.tsx
  src/components/common/bottomButtonTab.style.ts
  src/pages/ChatKeywordPage.tsx
  src/pages/ChatSelectionPage.tsx
  src/pages/chatKeywordPage.style.ts
  src/pages/chatSelectionPage.style.ts
  src/pages/index.ts
  src/shared/api/chatApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useChatFlag.ts
  src/shared/query/useKeyword.ts
  src/shared/query/useSelection.ts
  src/shared/styles/theme.ts
  src/shared/utils/RouterList.tsx
Labels: feature

#343 Feat/dam
  src/components/chat/ExitConfirmModal.tsx
  src/components/feedback/FeedOptionReminder.tsx
  src/components/feedback/FeedReminderModal.tsx
  src/components/feedback/FeedRequirement.tsx
  src/components/feedback/StatusReminder.tsx
  src/pages/ChatKeywordPage.tsx
  src/pages/ChatSelectionPage.tsx
  src/shared/api/chatApi.ts
  src/shared/api/reportApi.ts
  src/shared/hooks/useUserData.ts
  src/shared/hooks/useUserFeedbacks.ts
  src/shared/query/useChatFlag.ts
  src/shared/query/useExitChatRoom.ts
  src/shared/query/useFeedOption.ts
  src/shared/query/useFeedRequirement.ts
  src/shared/query/useFeedUser.ts
  src/shared/query/useKeyword.ts
  src/shared/query/useSelection.ts
Labels: feature

#347 Feat/dam
  package.json
  src/components/chat/Card.tsx
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/chat/introductionScreen.style.ts
  src/components/chat/keywordScreen.style.ts
  src/components/chat/selectionScreen.style.ts
  src/components/chat/waitingScreen.style.ts
  src/components/common/Nav.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/shared/hooks/useEmotionChange.ts
  src/shared/query/useChatFlag.ts
  src/shared/store/chatAction.ts
  src/shared/store/chatSlice.ts
  src/shared/store/socketMiddleware.ts
  yarn.lock
Labels: feature
