Repository 134talk/frontend, pull requests merged in 2023-06, with the labels that each got.

#168 Feat/login
  src/pages/KakaoPage.tsx
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
  src/shared/api/userApi.ts
  src/shared/query/Test.tsx
  src/shared/query/useAuth.ts
  src/shared/utils/ProtectedRoute.tsx
  src/shared/utils/RouterList.tsx
  src/shared/utils/queryClient.ts
  src/ui/Background.tsx
  src/ui/background.style.ts
  src/ui/kakaoButton.style.ts
Labels: feature

#169 Deploy
  .github/workflows/deploy.yml
  public/assets/cards/card-selected.svg
  public/assets/emotions/angry.svg
  public/assets/emotions/hug.svg
  public/assets/emotions/like.svg
  public/assets/emotions/love.svg
  public/assets/emotions/right.svg
  public/assets/emotions/sad.svg
  public/assets/icons/rotate.svg
  public/assets/icons/shadow.svg
  src/components/chat/Card.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/common/BottomModal.tsx
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/pages/KakaoPage.tsx
  src/pages/LogInPage.tsx
  src/pages/loginPage.style.ts
  src/shared/api/Test.tsx
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/reportApi.ts
  src/shared/api/userApi.ts
  src/shared/constants/constants.ts
  src/shared/constants/icons.ts
  src/shared/query/Test.tsx
  src/shared/query/useAuth.ts
  src/shared/utils/Device.tsx
  src/shared/utils/ProtectedRoute.tsx
  src/shared/utils/RouterList.tsx
  src/shared/utils/queryClient.ts
  src/ui/Background.tsx
  src/ui/Emotion.tsx
  src/ui/Spinner.tsx
  src/ui/background.style.ts
  src/ui/index.ts
  src/ui/kakaoButton.style.ts
Labels: deploy

#170 feat. 카카오 로그인 개발 #4
  src/shared/api/instance.ts
  src/shared/api/userApi.ts
  src/shared/query/useAuth.ts
  src/shared/utils/Router.tsx
  src/shared/utils/RouterList.tsx
  src/shared/utils/queryClient.ts
Labels: feature

#171 Deploy
  src/shared/api/instance.ts
  src/shared/api/userApi.ts
  src/shared/query/useAuth.ts
  src/shared/utils/Router.tsx
  src/shared/utils/RouterList.tsx
  src/shared/utils/queryClient.ts
Labels: deploy

#172 Feat/UI
  public/index.html
  src/shared/styles/globalStyle.ts
  src/shared/utils/Device.tsx
Labels: feature

#173 Deploy
  public/index.html
  src/shared/styles/globalStyle.ts
  src/shared/utils/Device.tsx
Labels: deploy

#175 Develop
  package.json
  src/shared/styles/globalStyle.ts
  src/shared/utils/Device.tsx
  yarn.lock
Labels: deploy

#176 feat. 상태바 스타일 수정
  public/index.html
Labels: feature

#178 Feat/sign
  public/assets/icons/admin.svg
  public/assets/icons/member.svg
  public/assets/icons/smile.svg
  public/assets/logos/logo-color.svg
  src/components/sign/ButtonColumn.tsx
  src/components/sign/SignButtonColumn.tsx
  src/components/sign/buttonColumn.style.ts
  src/components/sign/title.style.ts
  src/pages/LogInPage.tsx
  src/pages/SignPage.tsx
  src/pages/SignSelectPage.tsx
  src/pages/signPage.style.ts
  src/pages/signSelectPage.style.ts
  src/shared/api/userApi.ts
  src/shared/constants/icons.ts
  src/shared/query/useAuth.ts
  src/shared/query/useSign.ts
  src/ui/Button.tsx
  src/ui/SignButton.tsx
  src/ui/index.ts
  src/ui/input.style.ts
  src/ui/signButton.style.ts
Labels: feature

#179 Feat/nickname
  public/assets/icons/character-silhouette.svg
  src/components/nickname/buttonWrap.style.ts
  src/components/nickname/radioSelection.style.ts
  src/components/nickname/surveyLegend.style.ts
  src/pages/NicknameGuidePage.tsx
  src/pages/nicknameGuidePage.style.ts
  src/shared/api/userApi.ts
  src/shared/constants/icons.ts
Labels: feature

#180 Develop
  public/assets/icons/admin.svg
  public/assets/icons/character-silhouette.svg
  public/assets/icons/member.svg
  public/assets/icons/smile.svg
  public/assets/logos/logo-color.svg
  src/components/nickname/buttonWrap.style.ts
  src/components/nickname/radioSelection.style.ts
  src/components/nickname/surveyLegend.style.ts
  src/components/sign/ButtonColumn.tsx
  src/components/sign/SignButtonColumn.tsx
  src/components/sign/buttonColumn.style.ts
  src/components/sign/title.style.ts
  src/pages/LogInPage.tsx
  src/pages/NicknameGuidePage.tsx
  src/pages/SignPage.tsx
  src/pages/SignSelectPage.tsx
  src/pages/nicknameGuidePage.style.ts
  src/pages/signPage.style.ts
  src/pages/signSelectPage.style.ts
  src/shared/api/userApi.ts
  src/shared/constants/icons.ts
  src/shared/query/useAuth.ts
  src/shared/query/useSign.ts
  src/ui/Button.tsx
  src/ui/SignButton.tsx
  src/ui/index.ts
  src/ui/input.style.ts
  src/ui/signButton.style.ts
Labels: deploy

#181 Feat/nickname
  src/components/nickname/SurveySheet.tsx
  src/pages/LogInPage.tsx
  src/pages/NicknameGuidePage.tsx
  src/pages/NicknameResultPage.tsx
  src/pages/nicknameResultPage.style.ts
  src/shared/api/instance.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useName.ts
  src/shared/query/useNickname.ts
Labels: feature

#182 Develop
  src/components/nickname/SurveySheet.tsx
  src/pages/LogInPage.tsx
  src/pages/NicknameGuidePage.tsx
  src/pages/NicknameResultPage.tsx
  src/pages/nicknameResultPage.style.ts
  src/shared/api/instance.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useName.ts
  src/shared/query/useNickname.ts
Labels: deploy

#183 Feat/bottom tab
  public/assets/icons/chat-active.svg
  public/assets/icons/chat.svg
  public/assets/icons/member-active.svg
  public/assets/icons/report-active.svg
  public/assets/icons/report.svg
  public/assets/icons/user-active.svg
  public/assets/icons/user.svg
  public/assets/icons/users-active.svg
  public/assets/icons/users.svg
  src/components/common/BottomTab.tsx
  src/components/common/bottomTab.style.ts
  src/shared/query/useAuth.ts
  src/shared/utils/RouterList.tsx
Labels: feature

#184 feat. 닉네임 등록, 수정 api 개발 #17
  src/pages/NicknameResultPage.tsx
  src/shared/api/userApi.ts
  src/shared/query/useNickname.ts
Labels: feature

#185 Feat/chat list
  public/assets/icons/cancel.svg
  src/components/chatList/CheckModal.tsx
  src/components/chatList/CreateModal.tsx
  src/components/common/SearchBar.tsx
  src/components/common/searchBar.style.ts
  src/pages/MembersPage.tsx
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/userApi.ts
  src/shared/hooks/Test.tsx
  src/shared/hooks/useSearchKeyword.ts
  src/shared/query/useTimer.ts
Labels: feature

#186 Develop
  public/assets/icons/cancel.svg
  public/assets/icons/chat-active.svg
  public/assets/icons/chat.svg
  public/assets/icons/member-active.svg
  public/assets/icons/report-active.svg
  public/assets/icons/report.svg
  public/assets/icons/user-active.svg
  public/assets/icons/user.svg
  public/assets/icons/users-active.svg
  public/assets/icons/users.svg
  src/components/chatList/CheckModal.tsx
  src/components/chatList/CreateModal.tsx
  src/components/common/BottomTab.tsx
  src/components/common/SearchBar.tsx
  src/components/common/bottomTab.style.ts
  src/components/common/searchBar.style.ts
  src/pages/MembersPage.tsx
  src/pages/NicknameResultPage.tsx
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/userApi.ts
  src/shared/hooks/Test.tsx
  src/shared/hooks/useSearchKeyword.ts
  src/shared/query/useAuth.ts
  src/shared/query/useNickname.ts
  src/shared/query/useTimer.ts
  src/shared/utils/RouterList.tsx
Labels: deploy

#187 feat. 카카오톡 친구 초대 개발 #23
  src/components/members/InviteModal.tsx
  src/components/sign/Message.tsx
  src/components/sign/SignInputColumn.tsx
  src/pages/LogInPage.tsx
  src/pages/SignPage.tsx
  src/ui/Input.tsx
Labels: deploy

#188 feat. 공통 검색바 컴포넌트 각 페이지에 맞춰 스타일 수정
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/SearchBar.tsx
  src/components/common/searchBar.style.ts
  src/pages/ChatListPage.tsx
Labels: feature

#189 Develop
  src/components/chatList/CreateModal.tsx
  src/components/chatList/createModal.style.ts
  src/components/common/SearchBar.tsx
  src/components/common/searchBar.style.ts
  src/components/sign/SignInputColumn.tsx
  src/pages/ChatListPage.tsx
Labels: deploy

#190 feat. 아이콘 색상 수정, 대화 목록 페이지 스타일 변경 및 대화방 제목, 대화 참가자 포함
  public/assets/icons/check.svg
  src/components/chatList/ChatBox.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/chatBox.style.ts
  src/components/chatList/createModal.style.ts
Labels: feature

#191 feat. 스타일 수정
  src/components/chatList/GuideModal.tsx
  src/components/chatList/guideModal.style.ts
Labels: feature

#193 참가자 조회 api 개발 #21
  src/components/chat/UserList.tsx
  src/components/chatList/CreateModal.tsx
  src/components/common/Profile.tsx
  src/pages/MembersPage.tsx
  src/pages/membersPage.style.ts
  src/shared/api/chatApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/hooks/useSearchKeyword.ts
  src/shared/query/useTeam.ts
Labels: feature

#194 feat. 대화목록 api 개발 #26 & #27 & #28
  src/components/chatList/ChatBox.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/GuideModal.tsx
  src/components/chatList/SettingModal.tsx
  src/pages/ChatListPage.tsx
  src/pages/MembersPage.tsx
  src/pages/NicknameGuidePage.tsx
  src/pages/chatListPage.style.ts
  src/shared/api/chatApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/hooks/useSortedMembers.ts
  src/shared/query/useChatList.ts
  src/shared/query/useName.ts
  src/shared/query/useTimer.ts
Labels: feature

#196 Feat/user
  public/assets/icons/sign-out.svg
  src/components/index.ts
  src/components/report/statusDetail.style.ts
  src/components/user/Background.tsx
  src/components/user/ReportMenu.tsx
  src/components/user/Test.tsx
  src/components/user/UserProfile.tsx
  src/components/user/UserStatus.tsx
  src/components/user/background.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/userProfile.style.ts
  src/components/user/userStatus.style.ts
  src/pages/UserPage.tsx
  src/pages/userPage.style.ts
  src/shared/constants/icons.ts
  src/ui/Button.tsx
Labels: feature

#197 feat. 대화 목록 검색 api 개발 #28
  src/pages/ChatListPage.tsx
  src/shared/query/useChatList.ts
Labels: feature

#199 feat. 대화 목록 검색 최적화
  package.json
  src/components/chatList/CreateModal.tsx
  src/pages/ChatListPage.tsx
  src/shared/query/useChatInvitation.ts
  src/shared/query/useChatList.ts
  yarn.lock
Labels: feature

#200 Develop
  package.json
  public/assets/icons/sign-out.svg
  src/components/chatList/CreateModal.tsx
  src/components/index.ts
  src/components/report/statusDetail.style.ts
  src/components/user/Background.tsx
  src/components/user/ReportMenu.tsx
  src/components/user/Test.tsx
  src/components/user/UserProfile.tsx
  src/components/user/UserStatus.tsx
  src/components/user/background.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/userProfile.style.ts
  src/components/user/userStatus.style.ts
  src/pages/ChatListPage.tsx
  src/pages/UserPage.tsx
  src/pages/userPage.style.ts
  src/shared/constants/icons.ts
  src/shared/query/useChatInvitation.ts
  src/shared/query/useChatList.ts
  src/ui/Button.tsx
  yarn.lock
Labels: deploy

#202 Feat/user
  src/components/report/feedbackDetail.style.ts
  src/components/user/userProfile.style.ts
  src/pages/userPage.style.ts
Labels: feature

#203 feat. theme 개발
  src/App.tsx
  src/shared/styles/globalStyle.ts
  src/shared/styles/style.d.ts
  src/shared/styles/theme.ts
Labels: feature

#204 feat. theme color, fontSize, fontWeight 적용
  src/components/chatList/chatBox.style.ts
  src/components/chatList/checkModal.style.ts
  src/components/chatList/createModal.style.ts
  src/components/chatList/guideModal.style.ts
  src/components/chatList/settingModal.style.ts
  src/components/common/BaseModal.tsx
  src/components/common/FullModal.tsx
  src/components/common/baseModal.style.ts
  src/components/common/bottomButtonTab.style.ts
  src/components/common/bottomTab.style.ts
  src/components/common/fullModal.style.ts
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/members/inviteModal.style.ts
  src/components/nickname/radioSelection.style.ts
  src/components/nickname/surveyLegend.style.ts
  src/components/report/background.style.ts
  src/components/report/barChart.style.ts
  src/components/report/feedbackSection.style.ts
  src/components/report/reportBox.style.ts
  src/components/report/reportTitle.style.ts
  src/components/report/section.style.ts
  src/components/sign/message.style.ts
  src/components/sign/title.style.ts
  src/components/user/background.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/userProfile.style.ts
  src/components/user/userStatus.style.ts
  src/pages/KakaoPage.tsx
  src/pages/chatListPage.style.ts
  src/pages/kakaoPage.style.ts
  src/pages/loginPage.style.ts
  src/pages/membersPage.style.ts
  src/pages/nicknameGuidePage.style.ts
  src/pages/nicknameResultPage.style.ts
  src/pages/signPage.style.ts
  src/pages/signSelectPage.style.ts
  src/pages/userPage.style.ts
  src/shared/styles/theme.ts
  src/ui/Background.tsx
  src/ui/Button.tsx
  src/ui/background.style.ts
  src/ui/button.style.ts
  src/ui/chip.style.ts
  src/ui/input.style.ts
  src/ui/kakaoButton.style.ts
Labels: feature

#205 feat. refresh token req 수정
  src/shared/api/instance.ts
  src/shared/api/userApi.ts
Labels: feature

#212 fix. background, scroll 스타일 수정 #210
  src/components/chatList/SettingModal.tsx
  src/components/chatList/chatBox.style.ts
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/index.ts
  src/components/report/Background.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/FeedbackDetail.tsx
  src/components/report/StatusDetail.tsx
  src/components/user/Background.tsx
  src/components/user/background.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/userProfile.style.ts
  src/components/user/userStatus.style.ts
  src/pages/ChatListPage.tsx
  src/pages/ReportDetailPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/loginPage.style.ts
  src/pages/nicknameGuidePage.style.ts
  src/pages/userPage.style.ts
  src/shared/utils/Device.tsx
  src/ui/InnerBackground.tsx
  src/ui/index.ts
  src/ui/innerBackground.style.ts
Labels: bug

#213 Develop
  src/components/chatList/SettingModal.tsx
  src/components/chatList/chatBox.style.ts
  src/components/common/bottomTab.style.ts
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/index.ts
  src/components/report/Background.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/FeedbackDetail.tsx
  src/components/report/StatusDetail.tsx
  src/components/user/Background.tsx
  src/components/user/background.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/userProfile.style.ts
  src/components/user/userStatus.style.ts
  src/pages/ChatListPage.tsx
  src/pages/ReportDetailPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/loginPage.style.ts
  src/pages/nicknameGuidePage.style.ts
  src/pages/userPage.style.ts
  src/shared/utils/Device.tsx
  src/ui/InnerBackground.tsx
  src/ui/index.ts
  src/ui/innerBackground.style.ts
Labels: deploy

#215 feat. user data 핸들링 변경
  src/shared/api/instance.ts
  src/shared/hooks/useUserData.ts
  src/shared/utils/ProtectedRoute.tsx
Labels: feature

#216 feat. 채팅 목록, 설정 모달 수정
  src/components/chatList/SettingModal.tsx
  src/components/common/NavBar.tsx
  src/components/common/navBar.style.ts
  src/pages/ChatListPage.tsx
  src/shared/query/useChatList.ts
Labels: bug, feature

#218 feat. 전역 에러 처리 #217
  src/shared/api/instance.ts
  src/shared/utils/errorHandler.ts
Labels: feature

#220 feat. 탭 스타일 수정
  src/components/user/UserProfile.tsx
  src/components/user/userProfile.style.ts
  src/pages/UserPage.tsx
  src/pages/userPage.style.ts
Labels: feature

#222 feat. 공통 loader 개발 #221
  src/App.tsx
  src/pages/KakaoPage.tsx
  src/pages/kakaoPage.style.ts
  src/shared/utils/errorHandler.ts
  src/ui/Loader.tsx
  src/ui/index.ts
Labels: feature

#223 Develop
  src/App.tsx
  src/components/chatList/SettingModal.tsx
  src/components/common/BottomModal.tsx
  src/components/common/NavBar.tsx
  src/components/common/SearchBar.tsx
  src/components/common/navBar.style.ts
  src/components/common/searchBar.style.ts
  src/components/user/UserProfile.tsx
  src/components/user/userProfile.style.ts
  src/pages/ChatListPage.tsx
  src/pages/KakaoPage.tsx
  src/pages/UserPage.tsx
  src/pages/kakaoPage.style.ts
  src/pages/userPage.style.ts
  src/shared/api/instance.ts
  src/shared/hooks/useUserData.ts
  src/shared/query/useChatList.ts
  src/shared/utils/ProtectedRoute.tsx
  src/shared/utils/errorHandler.ts
  src/ui/Loader.tsx
  src/ui/index.ts
Labels: deploy

#224 feat. 로그아웃 api 개발 #66
  src/components/user/UserProfile.tsx
  src/pages/KakaoPage.tsx
  src/shared/api/userApi.ts
  src/shared/query/useAuth.ts
  src/shared/utils/logout.ts
Labels: feature

#225 feat. 유저 프로필 api 개발 #64
  src/components/user/UserProfile.tsx
  src/components/user/UserStatus.tsx
  src/pages/UserPage.tsx
  src/shared/api/userApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useProfile.ts
  src/shared/query/useTeam.ts
Labels: feature

#226 feat. 닉네임, 피드백 리포트 조회 api 개발
  src/components/report/FeedbackDetail.tsx
  src/components/report/FeedbackSection.tsx
  src/components/report/StatusDetail.tsx
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/reportApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useReport.ts
Labels: feature

#227 feat. 유저 리포트 목록 조회 api 개발 #67
  src/components/user/ReportMenu.tsx
  src/components/user/reportMenu.style.ts
  src/shared/query/useUserChatData.ts
  src/shared/utils/errorHandler.ts
Labels: feature

#229 feat. 리포트 상세 조회 api 개발 #59 & #60 & #61 & #62
  src/components/report/BarChart.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/FeedbackDetail.tsx
  src/components/report/StatusDetail.tsx
  src/components/report/barChart.style.ts
  src/shared/api/reportApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useReport.ts
  src/shared/utils/errorHandler.ts
Labels: feature

#243 feat. 유저 리포트 상세 view #68
  src/components/common/BottomTab.tsx
  src/components/common/Bubble.tsx
  src/components/common/EmotionData.tsx
  src/components/common/NavBar.tsx
  src/components/common/bubble.style.ts
  src/components/common/emotionData.style.ts
  src/components/index.ts
  src/components/report/ChatDetail.tsx
  src/components/report/ReportBox.tsx
  src/components/report/Section.tsx
  src/components/report/StatusDetail.tsx
  src/components/report/chatDetail.style.ts
  src/components/report/reportBox.style.ts
  src/components/report/section.style.ts
  src/components/report/statusDetail.style.ts
  src/components/user/Chip.tsx
  src/components/user/EffectGraph.tsx
  src/components/user/Emotion.tsx
  src/components/user/Feedback.tsx
  src/components/user/ReportMenu.tsx
  src/components/user/Satisfaction.tsx
  src/components/user/Sentence.tsx
  src/components/user/chip.style.ts
  src/components/user/effectGraph.style.ts
  src/components/user/emotion.style.ts
  src/components/user/feedback.style.ts
  src/components/user/satisfaction.style.ts
  src/components/user/sentence.style.ts
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/UserReportPage.tsx
  src/pages/index.ts
  src/pages/userReportPage.style.ts
  src/shared/api/reportApi.ts
  src/shared/constants/constants.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useUserChatData.ts
  src/shared/utils/RouterList.tsx
  src/ui/ProfileImg.tsx
Labels: feature

#244 Deploy
  src/components/common/BottomTab.tsx
  src/components/common/Bubble.tsx
  src/components/common/EmotionData.tsx
  src/components/common/NavBar.tsx
  src/components/common/bubble.style.ts
  src/components/common/emotionData.style.ts
  src/components/index.ts
  src/components/report/BarChart.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/FeedbackDetail.tsx
  src/components/report/FeedbackSection.tsx
  src/components/report/ReportBox.tsx
  src/components/report/Section.tsx
  src/components/report/StatusDetail.tsx
  src/components/report/barChart.style.ts
  src/components/report/chatDetail.style.ts
  src/components/report/reportBox.style.ts
  src/components/report/section.style.ts
  src/components/report/statusDetail.style.ts
  src/components/user/Chip.tsx
  src/components/user/EffectGraph.tsx
  src/components/user/Emotion.tsx
  src/components/user/Feedback.tsx
  src/components/user/ReportMenu.tsx
  src/components/user/Satisfaction.tsx
  src/components/user/Sentence.tsx
  src/components/user/UserProfile.tsx
  src/components/user/UserStatus.tsx
  src/components/user/chip.style.ts
  src/components/user/effectGraph.style.ts
  src/components/user/emotion.style.ts
  src/components/user/feedback.style.ts
  src/components/user/reportMenu.style.ts
  src/components/user/satisfaction.style.ts
  src/components/user/sentence.style.ts
  src/pages/KakaoPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/UserReportPage.tsx
  src/pages/index.ts
  src/pages/userReportPage.style.ts
  src/shared/api/chatApi.ts
  src/shared/api/instance.ts
  src/shared/api/reportApi.ts
  src/shared/api/userApi.ts
  src/shared/constants/constants.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useAuth.ts
  src/shared/query/useProfile.ts
  src/shared/query/useReport.ts
  src/shared/query/useTeam.ts
  src/shared/query/useUserChatData.ts
  src/shared/utils/RouterList.tsx
  src/shared/utils/logout.ts
  src/ui/ProfileImg.tsx
Labels: deploy

#246 Feat/user
  src/pages/UserReportPage.tsx
  src/pages/userReportPage.style.ts
  src/shared/query/useUserChatData.ts
Labels: feature

#247 feat. 하단탭 새 대화 알림 소켓 개발 #105
  src/components/common/BottomTab.tsx
  src/components/common/bottomTab.style.ts
  src/shared/query/useAuth.ts
  src/shared/store/chatAction.ts
  src/shared/store/chatSlice.ts
  src/shared/store/socketMiddleware.ts
Labels: feature

#248 feat. 공통 네비게이션 바 스타일 수정
  src/components/chatList/CreateModal.tsx
  src/components/chatList/GuideModal.tsx
  src/components/chatList/SettingModal.tsx
  src/components/common/NavBar.tsx
  src/components/common/navBar.style.ts
  src/pages/ChatListPage.tsx
  src/pages/MembersPage.tsx
  src/pages/ReportDetailPage.tsx
  src/pages/ReportPage.tsx
  src/pages/UserPage.tsx
  src/pages/UserReportPage.tsx
Labels: feature

#250 feat. 앱로고 & 이름 수정
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: feature

#251 feat. 404 페이지 개발 #249
  public/assets/icons/not-found.svg
  src/pages/NotFoundPage.tsx
  src/pages/index.ts
  src/pages/notFoundPage.style.ts
  src/shared/constants/icons.ts
  src/shared/utils/RouterList.tsx
Labels: feature

#253 Feat/chat
  public/favicon.ico
Labels: feature

#254 Deploy
  public/favicon.ico
Labels: deploy

#255 Feat/chat
  public/index.html
  public/logo.ico
  public/manifest.json
Labels: feature

#256 Deploy
  public/index.html
  public/logo.ico
  public/manifest.json
Labels: deploy

#257 deploy
  public/icon192.png
  public/icon512.png
  public/index.html
  public/manifest.json
Labels: deploy

#258 Develop
  .github/workflows/deploy.yml
Labels: deploy

#259 feat. 타입 & 상수명 수정, 주석 추가
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/ExitConfirmModal.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/feedback/FeedOptionReminder.tsx
  src/pages/ChatPage.tsx
  src/shared/api/reportApi.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useFeedOption.ts
  src/shared/query/useFeedRequirement.ts
  src/shared/query/useFeedUser.ts
  src/shared/store/chatSlice.ts
Labels: feature

#260 Feat/user
  public/assets/background.svg
  src/components/common/bubble.style.ts
  src/components/user/EffectGraph.tsx
  src/components/user/Feedback.tsx
  src/components/user/ReportMenu.tsx
  src/pages/UserReportPage.tsx
  src/shared/constants/icons.ts
  src/shared/query/useUserChatData.ts
  src/shared/utils/Device.tsx
Labels: feature

#261 feat. 유저 대화 리포트 상세 조회 api 개발
  src/components/user/Emotion.tsx
  src/pages/UserReportPage.tsx
  src/shared/query/useUserChatData.ts
Labels: feature

#262 axios 타입 추가 및 fetching data 변수명 수정
  src/components/chatList/CheckModal.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/SettingModal.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/StatusDetail.tsx
  src/pages/SignPage.tsx
  src/shared/api/chatApi.ts
  src/shared/api/userApi.ts
  src/shared/query/useAuth.ts
  src/shared/query/useChatInvitation.ts
  src/shared/query/useChatList.ts
  src/shared/query/useName.ts
  src/shared/query/useNickname.ts
  src/shared/query/useReport.ts
  src/shared/query/useSign.ts
  src/shared/query/useTimer.ts
Labels: feature, refactoring

#263 Deploy
  public/assets/background.svg
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/ExitConfirmModal.tsx
  src/components/chat/IntroductionScreen.tsx
  src/components/chat/KeywordScreen.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/chat/UserList.tsx
  src/components/chat/WaitingScreen.tsx
  src/components/chatList/CheckModal.tsx
  src/components/chatList/CreateModal.tsx
  src/components/chatList/SettingModal.tsx
  src/components/common/bubble.style.ts
  src/components/feedback/FeedOptionReminder.tsx
  src/components/report/ChatDetail.tsx
  src/components/report/StatusDetail.tsx
  src/components/user/EffectGraph.tsx
  src/components/user/Emotion.tsx
  src/components/user/Feedback.tsx
  src/components/user/ReportMenu.tsx
  src/pages/ChatPage.tsx
  src/pages/SignPage.tsx
  src/pages/UserReportPage.tsx
  src/shared/api/chatApi.ts
  src/shared/api/reportApi.ts
  src/shared/api/userApi.ts
  src/shared/constants/icons.ts
  src/shared/constants/queryKeys.ts
  src/shared/query/useAuth.ts
  src/shared/query/useChatInvitation.ts
  src/shared/query/useChatList.ts
  src/shared/query/useFeedOption.ts
  src/shared/query/useFeedRequirement.ts
  src/shared/query/useFeedUser.ts
  src/shared/query/useName.ts
  src/shared/query/useNickname.ts
  src/shared/query/useReport.ts
  src/shared/query/useSign.ts
  src/shared/query/useTimer.ts
  src/shared/query/useUserChatData.ts
  src/shared/store/chatSlice.ts
  src/shared/utils/Device.tsx
Labels: deploy

#264 Feat/chat
  src/components/chat/ChatNotifyScreen.tsx
  src/components/chat/ChatScreen.tsx
  src/components/chat/ChatSideNav.tsx
  src/components/chat/ChatTutorial.tsx
  src/components/chat/EmotionModal.tsx
  src/components/chat/SelectionScreen.tsx
  src/components/common/Profile.tsx
  src/components/feedback/FeedOptionCheck.tsx
  src/components/feedback/FeedOptionReminder.tsx
  src/components/feedback/FeedReminderModal.tsx
  src/components/feedback/FeedRequirement.tsx
  src/components/feedback/StatusReminder.tsx
  src/components/feedback/feedOptionReminder.style.ts
  src/components/feedback/feedReminderModal.style.ts
  src/components/feedback/feedRequirement.style.ts
  src/components/index.ts
  src/pages/ChatPage.tsx
  src/pages/FeedbackPage.tsx
  src/shared/api/reportApi.ts
  src/shared/constants/constants.ts
  src/shared/query/useFeedOption.ts
  src/shared/query/useFeedRequirement.ts
  src/shared/query/useFeedUser.ts
  src/shared/store/chatSlice.ts
  src/shared/utils/RouterList.tsx
  src/ui/Button.tsx
  src/ui/button.style.ts
  src/ui/emotion.style.ts
Labels: feature
